### ISSUE TITLE
does it work?

### ISSUE THREAD

**Issue by Roki100** [Discenz/SnipeJS#4]
does it work and can it beat chearful.ninja?

**Comment by Virachoca** [comment]
Currently the snipes are too late, still working on function to estimate delay and send that much sooner. Still in early development, and there are many things that need to be done to optimize the code. Likewise there are different approaches that have yet to be implemented, it will take some testing to determine what the most successful approach is for securing a snipe.

**Comment by Roki100** [comment]
> Currently the snipes are too late, still working on function to estimate delay and send that much sooner. Still in early development, and there are many things that need to be done to optimize the code. Likewise there are different approaches that have yet to be implemented, it will take some testing to determine what the most successful approach is for securing a snipe.

as far i know every sniper like chearful ninja is just spamming requests ~1-1.5 sec before name is releasing to get perfect delay on one of them

**Comment by Discenz** [comment]
Script is functional, but still needs considerable optimization, Closed.
